version: 0.0.{build}
branches:
  only:
    - master
  except:
    - gh-pages

image: Visual Studio 2017
init:
  - git config --global core.autocrlf input
cache:
  - /home/appveyor/.nuget/packages/

platform: Any CPU
configuration: Release
build:
  project: GraphqlClientExtensions.sln

before_build:
  - gitversion /output buildserver
  - [xml]$projectFile = Get-Content .\src\GraphQL.Client.Extensions\GraphQL.Client.Extensions.csproj
  - $projectFile.Project.ChildNodes.Item(0).Version = %GitVersion_SemVer%
  - $projectFile.Save(".\src\GraphQL.Client.Extensions\GraphQL.Client.Extensions.csproj")
build_script:
  - dotnet build

test_script:
  - dotnet test --no-build --no-restore

artifacts:
  - path: .\src\GraphQL.Client.Extensions\GraphQL.Client.Extensions\bin\Release\GraphQL.Client.Extensions.%GitVersion_NuGetVersion%.nupkg
    name: GraphQL.Client.Extensions.%GitVersion_NuGetVersion%.nupkg

deploy:
  - provider: NuGet
    server: https://www.myget.org/F/charlesdevandiere/api/v3/index.json
    api_key:
      secure: NCks/WutI84tjyT9Zji+vGM1UUHgHTCxUF3J9fCc/G4vpj6+GmEHrlKIf/dz/chF
    skip_symbols: false
    symbol_server: https://www.myget.org/F/charlesdevandiere/symbols/
    artifact: .\src\GraphQL.Client.Extensions\GraphQL.Client.Extensions\bin\Release\GraphQL.Client.Extensions.%GitVersion_NuGetVersion%.nupkg

  - provider: GitHub
    artifact: /.*\.nupkg/
    draft: false
    prerelease: false
    on:
      branch: master
      APPVEYOR_REPO_TAG: true