version: 0.0.{build}
branches:
  only:
    - master
    - develop
    - release/*
  except:
    - gh-pages

image: Ubuntu1804
init:
  - git config --global core.autocrlf input
cache:
  - /home/appveyor/.nuget/packages/
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"
platform: Any CPU
configuration: Release
build:
  project: GraphqlClientExtensions.sln
  #publish_nuget: true
  #publish_nuget_symbols: true
  #include_nuget_references: true
build_script:
  - dotnet build
test_script:
  - dotnet test --no-build --no-restore
